iiot_server:
  tcp_server:
    ip_address: 'localhost'
    port: 1233

  redis_server:
    ip_address: 'x.x.x.x'
    port: 6379
    pwd: 'pwd'

  rabbit_mq:
    ip_address: 'x.x.x.x'
    port: 5672
    id: 'whaleshark'
    pwd: 'pwd'
    exchange: 'facility'
    exchange_type: 'direct'

  influxdb:
    ip_address: 'x.x.x.x'
    port: 8086
    id: 'whaleshark'
    pwd: 'pwd'
    db: 'facility'
    
  operatingdb:
    host: 'x.x.x.x'
    port: 3306
    id: 'root'
    pwd: 'pwd'
    db: 'whaleshark_lite2'
